optimizer: Adam
learning_rate: 0.0003
epochs: 50
batch_size: 128
num_workers: 8
z_dim: 100
data_path: data
checkpoint_path: checkpoints
model_save_path: models
image_save_path: images
model_save_epochs: 1
print_steps: 100
visualize_epochs: 2
wandb: True
save_img_path: ./images
resume: False
#id: 3fgkvllv